apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-project-app2
  labels:
    app: python-project-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-project-app2
  template:
    metadata:
      labels:
        app: python-project-app2
    spec:
      containers:
        - name: python-project-app2
          image: registry.localhost:5001/python-project-app2:local
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: HOST2
              value: "0.0.0.0"
            - name: PORT2
              value: "8000"
            - name: DEBUG
              value: "false"
            - name: EXAMPLE_VARIABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: python-project-app2-secrets
                  key: EXAMPLE_VARIABLE_NAME
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
