apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: python-project-config
    literals:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - OTEL_SERVICE_NAME=python-project
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol.monitoring.svc.cluster.local:4317

secretGenerator:
  - name: python-project-secrets
    literals:
      - EXAMPLE_VARIABLE_NAME=""

labels:
  - pairs:
      app.kubernetes.io/name: python-project
      app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
