FROM python:3.14-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml ./
COPY uv.lock ./
RUN uv sync --no-dev --frozen --compile-bytecode

COPY src2/ ./src2/

ENV PYTHONPATH=.
ENV PATH="/app/.venv/bin:$PATH"

CMD ["sh", "-c", "python src2/manage.py migrate posts zero --no-input || true && python src2/manage.py migrate users zero --no-input || true && python src2/manage.py migrate && python src2/main.py"]