version: '3'

env:
  UV_ENV_FILE: .dev.env

tasks:

  cleanup:
    desc: Full project cleanup (docker, git, ports, caches)
    cmds:
      - powershell -ExecutionPolicy Bypass -File tasks/cleanup.ps1

  dev-env:
    desc: Setup uv environment (Python, sync, lock)
    cmds:
      - powershell -ExecutionPolicy Bypass -File tasks/dev_uv_environment.ps1
      - powershell -ExecutionPolicy Bypass -File .venv/Scripts/Activate.ps1

  local-static-tests:
    desc: Static analysis + unit tests
    cmds:
      - powershell -ExecutionPolicy Bypass -File tasks/static_analysis_and_tests.ps1

  local-dev-windows-run:
    desc: Local dev Windows run
    cmds:
      - powershell -ExecutionPolicy Bypass -File tasks/run_windows_dev_application.ps1
  
  k3d:
    desc: Load k3d cluster
    cmds:
      - powershell -ExecutionPolicy Bypass -File tasks/k3d.ps1

  kustomize-dev:
    desc: Load kustomize dev overlay
    cmds:
      - powershell -ExecutionPolicy Bypass -File tasks/kustomize.ps1

  tilt:
    desc: Load Tilt
    cmds:
      - powershell -ExecutionPolicy Bypass -File tasks/tilt.ps1

  full-dev-windows:
    desc: Native Windows development flow
    deps:
      - cleanup
    cmds:
      - task: dev-env
      - task: local-static-tests
      - task: local-dev-windows-run
      - task: k3d
      - task: kustomize-dev
      - task: tilt

# .\scripts\kustomize-apply.ps1 -Overlay prod -DryRun ; 
# .\scripts\kustomize-apply.ps1 -Overlay staging ; 

# .\scripts\k3d-redeploy.ps1 ; 
# .\scripts\k3d-down.ps1 ; 

# .\scripts\tilt-down.ps1 ; 