apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-project
  labels:
    app: python-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-project
  template:
    metadata:
      labels:
        app: python-project
    spec:
      containers:
        - name: python-project
          # Image pushed via: docker tag <image> localhost:5001/python-project:local
          #                   docker push localhost:5001/python-project:local
          image: registry.localhost:5001/python-project:local
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: EXAMPLE_VARIABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: python-project-secrets
                  key: EXAMPLE_VARIABLE_NAME
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
