apiVersion: v1
kind: Service
metadata:
  name: python-project
  labels:
    app: python-project
spec:
  selector:
    app: python-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
