apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-project-app2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: python-project-app2
          env:
            - name: LOG_LEVEL
              value: DEBUG
            - name: PORT2
              value: "8000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 3
