apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

namePrefix: app2-dev-

labels:
  - pairs:
      environment: dev

resources:
  - ../../base/app2

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: python-project-app2
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: python-project-app2

images:
  - name: registry.localhost:5001/python-project-app2
    newTag: local
