apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

namePrefix: dev-

commonLabels:
  environment: dev

bases:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: python-project

secretGenerator:
  - name: python-project-secrets
    namespace: dev
    envs:
      - .dev.secrets.env
    options:
      disableNameSuffixHash: true

images:
  - name: registry.localhost:5001/python-project
    newTag: local
