apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-

commonLabels:
  environment: prod

bases:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: python-project
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: python-project
  - path: hpa.yaml

secretGenerator:
  - name: python-project-secrets
    namespace: prod
    envs:
      - .prod.secrets.env
    options:
      disableNameSuffixHash: true

images:
  - name: registry.localhost:5001/python-project
    newTag: "1.0.0"
