apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: python-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: python-project GitOps project
  sourceRepos:
    - https://github.com/DariuszMak/local-kubernetes-cluster
  destinations:
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: staging
    - server: https://kubernetes.default.svc
      namespace: prod
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
